### ISSUE TITLE
Regex fails to match successful deployment

### ISSUE THREAD

**Issue by daneden** [Developmint/wait-for-netlify-preview#14]
I was experiencing an issue in which `wait-for-netlify-preview` got caught endlessly waiting for a successful netlify deploy status. After some debugging, I found that the reason it never succeeded was because the `hasDeployPreview` regex never matches.

The current regex matches `/^netlify\/.*\/deploy-preview$/`, but in the API, the netlify build status for my repo has a `context` value of `"deploy/netlify"`.

A couple of suggestions here:
- Make `hasDeployPreview` more generous and match just `netlify`
- Impose a limit on `pWaitFor` so that it doesn’t hang indefinitely

I’m not sure if my status API context just happens to differ for some reason, will investigate further.

**Comment by manniL** [comment]
@daneden Thanks for the report!

I've checked a recent commit (PR) of mine and can see a value of `netlify/NETLIFY_NAME/deploy-preview` (see https://api.github.com/repos/Developmint/developmint.de/commits/33388f0c0e747c9d0a20766336e0f003bdec1353/status).

![image](https://user-images.githubusercontent.com/640208/54677899-343ee400-4b04-11e9-8024-3e082754bf94.png)

Can you show me an API response of your case?

Regarding the suggestions:

> Make hasDeployPreview more generous and match just netlify
Could be a good solution but possibly gives false positives when other checks with a "netlify" context are running.

> Impose a limit on pWaitFor so that it doesn’t hang indefinitely
Mostly I leave that up to the CI (to terminate after ~10 min or so). It's hard to impose a limit without knowing how log the actual deploy preview is building.

PS: Didn't know somebody other than me is using the package :D Happy to see that!

**Comment by daneden** [comment]
I think this happened because my Netlify installation was as a GitHub integration rather than a GitHub app (I first started using Netlify before GitHub apps were a thing!)

I’ve just re-installed Netlify as a GitHub app for the repo in question and will see if that changes things.

Also, you can thank @poteto for calling attention to this package in her [Medium → Gatsby migration post](https://www.no.lol/2019-03-16-medium-to-gatsby/)!

**Comment by daneden** [comment]
It looks like even after changing to a GitHub app instead of integration, the `context` of my commit status is still `deploy/netlify`: https://api.github.com/repos/daneden/daneden.me/commits/a62925aa55bce75eee793a62a5e70c5b0b67807d/status

I ended up forking the repo to get it working for my site, but can test this on some other/more recent Netlify deployments to see if it’s just a problem for my site!

**Comment by manniL** [comment]
> It looks like even after changing to a GitHub app instead of integration, the context of my commit status is still deploy/netlify: api.github.com/repos/daneden/daneden.me/commits/a62925aa55bce75eee793a62a5e70c5b0b67807d/status

To support the "legacy" Netlify integrations (and therefore older build contexts I guess, looks like they won't change) I wouldn't have a problem with making the regex less strict and match both "versions" of the deploy context :relaxed: 	

> Also, you can thank @poteto for calling attention to this package in her Medium → Gatsby migration post!

Neat! Wanted to blog about exactly the same thing :yum: (Lighthousebot + Netlify deploy previews = :cupid: )

**Comment by amberleyromo** [comment]
Having the same issue as @daneden, super curious as to what causes these contexts to be different.

chatted with @sw-yx , he recommended I tag in @futuregerald, might be able to shed some light? :)

**Comment by manniL** [comment]
Sorry for the delay folks. Just released v1.2.1
